### ISSUE TITLE
I guess little changes broke something

### ISSUE THREAD

**Issue by AzEExE** [iValencitoh/Steam-Hour-Booster-2FA-Support#21]
> vaporbooster@1.0.3 start
> node src/accountHandler.js

node:internal/modules/cjs/loader:1080
  throw err;
  ^

Error: Cannot find module 'steam-user'
Require stack:
- ...\vaporBooster-main\src\hourBooster.js
- ...\vaporBooster-main\src\accountHandler.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
    at Module._load (node:internal/modules/cjs/loader:922:27)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (C:\Users\ibrah\OneDrive\İş masası\stuff\loader\vaporBooster-main\src\hourBooster.js:2:19)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '...\\vaporBooster-main\\src\\hourBooster.js',
    '...\\vaporBooster-main\\src\\accountHandler.js'
  ]
}
happens after "npm run start" command

**Comment by valnssh** [comment]
You forgot to install the dependencies. See https://github.com/valndev/vaporBooster#installation

**Comment by AzEExE** [comment]
Ive used this booster before and it worked perfectly back then but after formatting my pc (i have nodejs installed already) i redownloaded this booster and that's the error i see.
The thing is i tried after "npm install" command. Is there chance that npm version is the issue?

**Comment by valnssh** [comment]
Hey there,

Thanks for reaching out. The npm version shouldn't be the problem here. If you've already run 'npm install' and you're still getting the "Cannot find module 'steam-user'" error, there might be something else going on.

Since you mentioned you formatted your PC and re-downloaded the booster, let's try a few steps to get things working:

* Start fresh by cloning the repository again.
* Go to the project directory and run 'npm install' to install all the necessary dependencies. Make sure there are no errors during the installation. *(Take a screenshot of the terminal after running the command. If the problem persists, please send me the screenshot.)*
* Configure your accounts and preferences according to your needs. Refer to the project's documentation or README file for any specific instructions on how to set them up.
* Once everything is set up, give 'npm run start' a try and see if the issue still persists.

If you encounter any errors during the 'npm install' command, please share the error output or any relevant error messages with me. That will help me investigate the problem further and provide more specific guidance.

I hope this helps! Let me know if you have any other questions or run into any more issues.

**Comment by AzEExE** [comment]
Again the same problem. There was no error during installing process nor any error showed up. 
![image](https://github.com/valndev/vaporBooster/assets/51942945/75559a06-3d76-4048-859b-03db6b9d69f4)
But after that here this is
![image](https://github.com/valndev/vaporBooster/assets/51942945/62474573-22aa-4f53-930c-321dd542c6e0)

**Comment by valnssh** [comment]
Try installing the dependencies manually. You can do this by running the following command in your terminal:
```shell
npm install easytimer.js jwt-decode readline-sync steam-totp steam-user --save
```
This command will install the required dependencies and save them to your project's `package.json` file.

**Comment by AzEExE** [comment]
Welp sadly error still on there, same error after same command

**Comment by valnssh** [comment]
The only thing I can suggest is that you completely uninstall npm, node, and everything related to it. Then install the latest LTS version of NodeJS, clone the repository again, and retry from the beginning.

**Comment by AzEExE** [comment]
Just wanted to let you know, it was caused by windows desktop named with letters that cmd can't pick up. (Due to windows change desktop folder name to just as how it is translated in other language.) After changing desktop name itself everything works without any flaw.
