### ISSUE TITLE
RateLimitExceeded

### ISSUE THREAD

**Issue by zoomingbye** [iValencitoh/Steam-Hour-Booster-2FA-Support#4]
Hello! I'm having this issue where I've got two accounts set up to idle, all information is correct, the "identity_secret" is from maFiles as well so it should be perfect, but once I launch the bot it spams authenticator code and then says rate limit exceeded, when I opened SDA  the code wasn't right though. Could it be that I'm getting a different code than SDA, am I not supposed to use "identity_secret" as the shared secret key?

**Comment by valnssh** [comment]
Hey!👋, I'm so sorry for my late response, the university is squeezing my time.  

One of the possible options that I can imagine is that the libraries may be somewhat outdated. Another option could be a limitation of Steam itself. And last but not least, a problem in the code that generates some kind of loop.  

If I were you, I would try to update all the libraries/dependencies and check to be in the latest version of NodeJS. I'm going to try to review this problem ASAP, but as I said before, I have very little free time.  
I would ask if you could attach a screenshot/text of the error present in the terminal so that I can view the log.

**Comment by zoomingbye** [comment]
Hello! It's all good, seems like there probably was a misconception and I might've copied the wrong steam code, I moved over to a different code and it works fine, if I can I'll try your code once again when I have some free time as well:)
Best of luck!
